name: Auto Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy Files directly to Nginx Root
        run: |
          cp -r ./* /var/www/car-game/