name: Auto Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files to Nginx Root
        run: |
          rsync -av --exclude='actions-runner' --exclude='.git' ./ /var/www/car-game/
          sudo chmod -R 755 /var/www/car-game